version: '2'

services:
    web:
        build:
            context: ./images/bamboo
            args:
                - BAMBOO_VERSION=${BAMBOO_VERSION}
                - WEB_RUN_USER=${WEB_RUN_USER}
                - WEB_RUN_GROUP=${WEB_RUN_GROUP}
                - PKGS=${WEB_PKGS}
        image: ianharrier/bamboo:${BAMBOO_VERSION}
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - ${WEB_PORT}:8085
            - ${WEB_BROKER_PORT}:54663
        environment:
            - PROXY_HOSTNAME=${WEB_PROXY_HOSTNAME}
            - PROXY_PORT=${WEB_PROXY_PORT}
            - PROXY_SCHEME=${WEB_PROXY_SCHEME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./volumes/web/data:/var/atlassian/application-data/bamboo
            - /var/run/docker.sock:/var/run/docker.sock
        security_opt:
            - label:disable
    db:
        image: postgres:9.6-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
        volumes:
            - ./volumes/db/data:/var/lib/postgresql/data:z
    cron:
        build:
            context: ./images/cron
        image: ianharrier/bamboo-cron:1.1.0
        restart: unless-stopped
        environment:
            - BACKUP_OPERATION=${BACKUP_OPERATION}
            - BACKUP_CRON_EXP=${BACKUP_CRON_EXP}
            - BACKUP_RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - TIMEZONE=${TIMEZONE}
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
            - BAMBOO_USERNAME=${BACKUP_BAMBOO_USERNAME}
            - BAMBOO_PASSWORD=${BACKUP_BAMBOO_PASSWORD}
        volumes:
            - ./:${PWD}:z
